name: bargou_gym
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # عدلت النسخة باش تمشي مع المكتبات الجديدة

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.0.0
  http: ^1.2.0
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.3.2 # 👈 صلحنا الفراغات وزدنا النسخة

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # نسخة متوافقة أكثر

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"