// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVoqcdKx_Y96RdiZZoNVTW06-oD9duvcs',
    appId: '1:122930893416:web:9412954aea60314854a1dd',
    messagingSenderId: '122930893416',
    projectId: 'bargou-gym',
    authDomain: 'bargou-gym.firebaseapp.com',
    storageBucket: 'bargou-gym.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgna3D5H0CCQEwm5cf0DQ0b45u2lzkzl8',
    appId: '1:122930893416:android:d69ef70c0a6bad6854a1dd',
    messagingSenderId: '122930893416',
    projectId: 'bargou-gym',
    storageBucket: 'bargou-gym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCexZhmCsBQgy0CvduFge17YVmq5ZgB8d0',
    appId: '1:122930893416:ios:f82a05353e85051854a1dd',
    messagingSenderId: '122930893416',
    projectId: 'bargou-gym',
    storageBucket: 'bargou-gym.firebasestorage.app',
    iosBundleId: 'com.example.bargouGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCexZhmCsBQgy0CvduFge17YVmq5ZgB8d0',
    appId: '1:122930893416:ios:f82a05353e85051854a1dd',
    messagingSenderId: '122930893416',
    projectId: 'bargou-gym',
    storageBucket: 'bargou-gym.firebasestorage.app',
    iosBundleId: 'com.example.bargouGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVoqcdKx_Y96RdiZZoNVTW06-oD9duvcs',
    appId: '1:122930893416:web:0b60b1edfc5edf2f54a1dd',
    messagingSenderId: '122930893416',
    projectId: 'bargou-gym',
    authDomain: 'bargou-gym.firebaseapp.com',
    storageBucket: 'bargou-gym.firebasestorage.app',
  );

}